name: Linux and MacOS

on:
  push:
    branches-ignore:
      - 'wip-*'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - master
      - development
  schedule:
    - cron: '0 11 * * *'

jobs:
  ci:
    strategy:
      fail-fast: false

      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
        name:
          - Ubuntu
          - macOS

        include:
          - name: Ubuntu
            os: ubuntu-18.04
            ccov: ON

          - name: macOS
            os: macos-latest
            ccov: OFF

    name: "${{ matrix.name }}: PHP ${{ matrix.php }}"
    runs-on: ${{ matrix.os }}

    env:
      RE2C_VERSION: 2.2
      ZEND_DONT_UNLOAD_MODULES: 1
      USE_ZEND_ALLOC: 0

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php }}'
          coverage: none

      - name: Cache RE2C Downloads
        uses: actions/cache@v2
        with:
          path: $HOME/.cache/re2c
          key: ${{ runner.os }}-php-${{ matrix.php }}-re2c-${env:RE2C_VERSION}

      - name: Setup Prerequisites (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update --quiet --yes 1>/dev/null
          sudo apt-get install --no-install-recommends --quiet --yes lcov gdb

      - name: Setup Prerequisites (macOS)
        if: runner.os == 'macOS' && matrix.ccov == 'ON'
        run: |
          brew install lcov
          sudo xcode-select -switch /Applications/Xcode.app

      - name: Setup Build System (Generic)
        run: |
          ulimit -c unlimited -S || true

          mkdir -p $HOME/.cache/re2c
          mkdir -p $HOME/.local/opt/re2c

          echo "PATH=$PATH:$HOME/bin:$(brew --prefix lcov)/bin" >> $GITHUB_ENV
          echo "MAKEFLAGS=-j$(getconf _NPROCESSORS_ONLN)" >> $GITHUB_ENV
          echo "CI=true" >> $GITHUB_ENV
          echo "ZEPHIR_PARSER_VERSION=$(head -1 VERSION)" >> $GITHUB_ENV

      - name: Setup Core Dump (Linux)
        if: runner.os == 'Linux'
        run: echo '/tmp/core.%e.%p.%t' | sudo tee /proc/sys/kernel/core_pattern

      - name: Install re2c
        run: .ci/install-re2c.sh

      - name: Build extensions
        run: |
          phpize

          if [ "${{ matrix.ccov }}" = "ON" ]; then
            ./configure \
              --enable-zephir-parser \
              --enable-zephir-parser-debug \
              --enable-coverage
          else
            ./configure \
              --enable-zephir-parser \
              --enable-zephir-parser-debug
          fi

          make -j$(getconf _NPROCESSORS_ONLN)

      - name: Preparing to collect coverage data
        if: matrix.ccov == 'ON'
        run: make coverage-initial

      - name: Run Tests
        run: |
          php -d extension=./modules/zephir_parser.so --ri 'Zephir Parser'
          make test NO_INTERACTION=1 REPORT_EXIT_STATUS=1

      - name: Print failures
        if: failure() && runner.os == 'Linux'
        run: .ci/after-failure.sh

      - name: Capture coverage data
        if: success() && matrix.ccov == 'ON'
        run: make coverage-capture

      - name: Upload code coverage report
        if: matrix.ccov == 'ON'
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./lcov.info
          flags: unittests
          fail_ci_if_error: false

      - name: Upload Zephir Parser
        uses: actions/upload-artifact@v2
        with:
          name: zephir-parser-v${env:ZEPHIR_PARSER_VERSION}-php-${{ matrix.php }}-${{ runner.os }}
          path: |
            ${{ github.workspace }}\modules\*.so
