name: Windows

on:
  push:
    branches-ignore:
      - 'wip-*'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - master
      - development
  schedule:
    - cron: '0 11 * * *'

jobs:
  ci:
    strategy:
      fail-fast: false

      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
        build-type: ['Win32', 'nts-Win32']
#        arch: ['x86', 'x64']
        include:
          - php: ['7.0', '7.1']
            vc-version: 14

          - php: ['7.2', '7.3', '7.4']
            vc-version: 15

          - php: ['8.0']
            vc-version: 16

    name: "Windows ${{ matrix.build-type }} ${{ matrix.arch }} with VC${{ matrix.vc-version }} and PHP ${{ matrix.php }}"
    runs-on: windows-2016

    steps:
      - run: echo "OK"
