name: Windows

on:
  push:
    branches-ignore:
      - 'wip-*'
    paths-ignore:
      - '*.md'

#  pull_request:
#    branches:
#      - master
#      - development

#  schedule:
#    - cron: '0 11 * * *'

env:
  PHP_SDK_VERSION: 2.2.0
  PHP_DEVPACK: C:\tools\php-devpack
  PHP_SDK_PATH: C:\tools\php-sdk
  EXTENSION_FILE: php_zephir_parser.dll

jobs:
  ci:
    strategy:
      fail-fast: false

      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
        arch: ['x86', 'x64']
        build_type: ['ts', 'nts']
        vc_num: [14, 15, 16]

        exclude:
          - php: '7.0'
            vc_num: 15
          - php: '7.0'
            vc_num: 16

          - php: '7.1'
            vc_num: 15
          - php: '7.1'
            vc_num: 16

          - php: '7.2'
            vc_num: 14
          - php: '7.2'
            vc_num: 16

          - php: '7.3'
            vc_num: 14
          - php: '7.3'
            vc_num: 16

          - php: '7.4'
            vc_num: 14
          - php: '7.4'
            vc_num: 16

          - php: '8.0'
            vc_num: 14
          - php: '8.0'
            vc_num: 15

    name: "PHP-${{ matrix.php }}-${{ matrix.build_type }}-Win32-VC${{ matrix.vc_num }}-${{ matrix.arch }}"
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
        env:
          PHPTS: ${{ matrix.build_type }}

      - name: Set Environment Variables
        run: |
          Write-Output "PHP_VERSION=$(php -r 'echo phpversion();')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "PHP_MINOR=${{ matrix.php }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "TEST_PHP_EXECUTABLE=${env:PHPROOT}\php.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "BUILD_TYPE=${{ matrix.build_type }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "VC_VERSION=${{ matrix.vc_num }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "PHP_ARCH=${{ matrix.arch }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "BUILD_VERSION=${GITHUB_RUN_NUMBER}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup Common Environmet
        run: |
          Import-Module .\.ci\win-ci-tools.psm1
          SetupCommonEnvironment

      # TODO: Use cache for PHP SDK and build tools
      - name: Install PHP SDK Binary Tools
        run: |
          Import-Module .\.ci\win-ci-tools.psm1
          InstallPhpSdk

      - name: Install PHP Dev pack
        run: |
          Import-Module .\.ci\win-ci-tools.psm1
          InstallPhpDevPack

      - name: Getting Details About Installed PHP
        run: Get-Php "${env:PHPROOT}"

      - name: Install CL
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          toolset: ${{ matrix.vc_num }}.0

      - name: Parse Zephir Parser (Lemon)
        shell: cmd
        run: |
          call C:\tools\php-sdk\bin\phpsdk_setvars.bat
          powershell.exe -File .\.ci\lemon-parser.ps1

      - name: Build Zephir Parser (phpize)
        shell: cmd
        run: |
          call C:\tools\php-sdk\phpsdk-vc${{ matrix.vc_num }}-${{ matrix.arch }}.bat
          call C:\tools\php-sdk\bin\phpsdk_setvars.bat
          call C:\tools\php-devpack\phpize.bat

      - name: Configure
        shell: cmd
        run: |
          call C:\tools\php-sdk\phpsdk-vc${{ matrix.vc_num }}-${{ matrix.arch }}.bat
          call C:\tools\php-sdk\bin\phpsdk_setvars.bat
          configure --with-codegen-arch=yes --with-prefix=C:\php --with-php-build=C:\php-devpack --disable-all --enable-zephir-parser=shared

      - name: Compile
        shell: cmd
        run: |
          call C:\tools\php-sdk\phpsdk-vc${{ matrix.vc_num }}-${{ matrix.arch }}.bat
          call C:\tools\php-sdk\bin\phpsdk_setvars.bat
          nmake

      - name: Check errors
        if: always()
        run: |
          if (Test-Path -Path "${env:GITHUB_WORKSPACE}\compile-errors.log") {
            Get-Content -Path "${env:GITHUB_WORKSPACE}\compile-errors.log"
          }
          if (Test-Path -Path "${env:GITHUB_WORKSPACE}\compile.log") {
            Get-Content -Path "${env:GITHUB_WORKSPACE}\compile.log"
          }

      - name: Check build artifacts
        run: |
          Import-Module .\.ci\win-ci-tools.psm1
          InitializeReleaseVars
          Get-ChildItem ${Env:GITHUB_WORKSPACE} -name -recurse php_zephir_parser.dll

      - name: Enable Zephir Parser
        run: |
          Import-Module .\.ci\win-ci-tools.psm1
          InitializeReleaseVars
          Copy-Item "${env:RELEASE_DLL_PATH}" "${env:PHPROOT}\ext\${env:EXTENSION_FILE}"
          EnablePhpExtension -Extension 'Zephir Parser' -Path "${env:PHPROOT}"

      - run: |
          Import-Module .\.ci\win-ci-tools.psm1
          PrepareReleasePackage `
                  -PhpVersion     $Env:PHP_VERSION `
                  -BuildType      $Env:BUILD_TYPE `
                  -Platform       $Env:PLATFORM `
                  -ConverMdToHtml $true `
                  -ReleaseFiles   "${Env:RELEASE_DLL_PATH}",`
                                  "${Env:GITHUB_WORKSPACE}\LICENSE",`
                                  "${Env:GITHUB_WORKSPACE}\CREDITS",`
                                  "${Env:GITHUB_WORKSPACE}\VERSION",`
                                  "${Env:GITHUB_WORKSPACE}\NO_WARRANTY"

      - name: Upload build artifacts after Failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.arch }}-vc${{ matrix.vc_num }}-php-${{ matrix.php }}-${{ matrix.build_type }}
          path: |
            ${{ github.workspace }}\compile-errors.log
            ${{ github.workspace }}\compile.log
            ${{ github.workspace }}\config.log
            ${{ github.workspace }}\parser\
          retention-days: 1
